id: I407E7E5A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:32:19+00:00'
last_modified: '2022-06-07T16:33:09.647770+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7036
  title: ཕྱུག་བྱ་གསོ་སྤེལ་ལག་རྩལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6776':
      image_group_id: I3CN7038
      title: ''
      total_pages: 154
      order: 1
      base_file: 6776.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
